name: CI - Teste ELK Mikrotik Syslog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7-dind
        privileged: true
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Subir stack Docker Compose
        run: |
          docker-compose up -d
          sleep 30  # Aguarda os serviços subirem

      - name: Instalar dependências Python
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install requests

      - name: Testar envio de log
        run: |
          python3 test_log.py

      - name: Verificar status dos containers
        run: |
          docker-compose ps
          docker-compose logs 